# Generated by Django 3.2.8 on 2021-10-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('born', models.IntegerField()),
                ('country', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
